name: dartservice_web
description: Dart service. Under construction stub.
publish_to: "none" 

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3

  # Утилиты для масштабирования элементов UI
  # в зависимости от размера экрана
  flutter_screenutil: 2.1.0

  # Шрифты от Google
  google_fonts: 1.1.0

  # Сервис локатор для создания и доступа
  # к компонентам приложения
  get_it: 4.0.2

  # Реактивная библиотека для передачи событий
  # и состояний с помощью потоков (Streams)
  rxdart: 0.24.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  assets:
    - assets/image/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
